apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: techchallenge2
  namespace: argocd
spec:
  description: TechChallenge2 GitOps project
  sourceRepos:
    - https://github.com/andrewlinzie/TechChallenge2.git
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
